# Pre-commit framework Configuration
# See https://pre-commit.com for more information
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
        exclude: python3/14_Code_Quality/python_2to3_ex.py
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      # - id: check-yaml
      #   args: [--allow-multiple-documents]
      - id: debug-statements
        exclude: |
          (?x)(
              ^python3/05_Debugging/ |
              ^python3/14_Code_Quality/python_2to3_ex.py
          )
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      #- id: check-shebang-scripts-are-executable

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black] # , --check-only
        description: Sort Python imports

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--check]
        exclude: python3/14_Code_Quality/python_2to3_ex.py
      - id: black-jupyter
        language_version: python3
        exclude: python3/14_Code_Quality/python_2to3_ex.py

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.10.0 # checks for Github Actions CI config files
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.9.2
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=131, --statistics]
  #       additional_dependencies: ["flake8-bugbear"]
  #       description: Lint Python Files

  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
  #       args: ["-ll"]
  #       files: .py$

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.942
  #   hooks:
  #     - id: mypy
